// 常用英语单词音标对照表（IPA 国际音标）
// 覆盖 PEP 小学3-6年级词汇
const phoneticDB = {
  // 三年级上 - Unit 1 Hello!
  hello: '/həˈloʊ/', hi: '/haɪ/', goodbye: '/ɡʊdˈbaɪ/', bye: '/baɪ/',
  name: '/neɪm/', my: '/maɪ/', your: '/jʊr/', I: '/aɪ/', am: '/æm/',
  what: '/wʌt/', is: '/ɪz/',
  // Unit 2 Colours
  red: '/red/', green: '/ɡriːn/', yellow: '/ˈjeloʊ/', blue: '/bluː/',
  black: '/blæk/', white: '/waɪt/', orange: '/ˈɔːrɪndʒ/', brown: '/braʊn/',
  colour: '/ˈkʌlər/', pink: '/pɪŋk/', purple: '/ˈpɜːrpl/',
  // Unit 3 Look at me
  face: '/feɪs/', eye: '/aɪ/', ear: '/ɪr/', nose: '/noʊz/',
  mouth: '/maʊθ/', head: '/hed/', hand: '/hænd/', arm: '/ɑːrm/',
  leg: '/leɡ/', foot: '/fʊt/', body: '/ˈbɑːdi/', look: '/lʊk/',
  at: '/æt/', me: '/miː/',
  // Unit 4 We love animals
  cat: '/kæt/', dog: '/dɔːɡ/', duck: '/dʌk/', pig: '/pɪɡ/',
  bird: '/bɜːrd/', bear: '/ber/', monkey: '/ˈmʌŋki/', tiger: '/ˈtaɪɡər/',
  panda: '/ˈpændə/', elephant: '/ˈelɪfənt/', zoo: '/zuː/', animal: '/ˈænɪml/',
  love: '/lʌv/', we: '/wiː/',
  // Unit 5 Let's eat!
  bread: '/bred/', cake: '/keɪk/', milk: '/mɪlk/', water: '/ˈwɔːtər/',
  egg: '/eɡ/', rice: '/raɪs/', fish: '/fɪʃ/', juice: '/dʒuːs/',
  food: '/fuːd/', chicken: '/ˈtʃɪkɪn/', eat: '/iːt/', drink: '/drɪŋk/',
  hungry: '/ˈhʌŋɡri/', some: '/sʌm/', please: '/pliːz/',
  // Unit 6 Happy birthday
  one: '/wʌn/', two: '/tuː/', three: '/θriː/', four: '/fɔːr/',
  five: '/faɪv/', six: '/sɪks/', seven: '/ˈsevn/', eight: '/eɪt/',
  nine: '/naɪn/', ten: '/ten/', brother: '/ˈbrʌðər/', sister: '/ˈsɪstər/',
  plate: '/pleɪt/', balloon: '/bəˈluːn/', birthday: '/ˈbɜːrθdeɪ/',
  happy: '/ˈhæpi/', old: '/oʊld/', year: '/jɪr/',
  // 三年级下 - Unit 1 Welcome back to school
  school: '/skuːl/', bag: '/bæɡ/', book: '/bʊk/', pen: '/pen/',
  pencil: '/ˈpensl/', ruler: '/ˈruːlər/', eraser: '/ɪˈreɪsər/',
  crayon: '/ˈkreɪɑːn/', teacher: '/ˈtiːtʃər/', student: '/ˈstuːdnt/',
  desk: '/desk/', chair: '/tʃer/', classroom: '/ˈklæsruːm/',
  // Unit 2 My family
  father: '/ˈfɑːðər/', mother: '/ˈmʌðər/', dad: '/dæd/', mom: '/mɑːm/',
  man: '/mæn/', woman: '/ˈwʊmən/', grandfather: '/ˈɡrænfɑːðər/',
  grandmother: '/ˈɡrænmʌðər/', family: '/ˈfæməli/', grandpa: '/ˈɡrænpɑː/',
  grandma: '/ˈɡrænmɑː/', he: '/hiː/', she: '/ʃiː/',
  // Unit 3 At the zoo
  tall: '/tɔːl/', short: '/ʃɔːrt/', fat: '/fæt/', thin: '/θɪn/',
  big: '/bɪɡ/', small: '/smɔːl/', long: '/lɔːŋ/', tail: '/teɪl/',
  cute: '/kjuːt/', funny: '/ˈfʌni/', beautiful: '/ˈbjuːtɪfl/',
  has: '/hæz/', have: '/hæv/', children: '/ˈtʃɪldrən/',
  // Unit 4 Where is my car?
  on: '/ɑːn/', in: '/ɪn/', under: '/ˈʌndər/', desk: '/desk/',
  chair: '/tʃer/', car: '/kɑːr/', boat: '/boʊt/', ball: '/bɔːl/',
  cap: '/kæp/', map: '/mæp/', toy: '/tɔɪ/', box: '/bɑːks/',
  where: '/wer/', put: '/pʊt/',
  // Unit 5 Do you like pears?
  apple: '/ˈæpl/', pear: '/per/', banana: '/bəˈnænə/', grape: '/ɡreɪp/',
  watermelon: '/ˈwɔːtərmelən/', strawberry: '/ˈstrɔːberi/', fruit: '/fruːt/',
  buy: '/baɪ/', like: '/laɪk/', taste: '/teɪst/', sweet: '/swiːt/',
  // Unit 6 How many?
  eleven: '/ɪˈlevn/', twelve: '/twelv/', thirteen: '/θɜːrˈtiːn/',
  fourteen: '/fɔːrˈtiːn/', fifteen: '/fɪfˈtiːn/', sixteen: '/sɪksˈtiːn/',
  seventeen: '/sevnˈtiːn/', eighteen: '/eɪˈtiːn/', nineteen: '/naɪnˈtiːn/',
  twenty: '/ˈtwenti/', many: '/ˈmeni/', count: '/kaʊnt/',
  number: '/ˈnʌmbər/', open: '/ˈoʊpən/', see: '/siː/',
  // 四年级上下
  door: '/dɔːr/', window: '/ˈwɪndoʊ/', light: '/laɪt/', picture: '/ˈpɪktʃər/',
  board: '/bɔːrd/', floor: '/flɔːr/', wall: '/wɔːl/', fan: '/fæn/',
  computer: '/kəmˈpjuːtər/', phone: '/foʊn/', TV: '/ˌtiːˈviː/',
  clean: '/kliːn/', near: '/nɪr/', really: '/ˈriːəli/',
  key: '/kiː/', candy: '/ˈkændi/', toy: '/tɔɪ/', notebook: '/ˈnoʊtbʊk/',
  storybook: '/ˈstɔːribʊk/', math: '/mæθ/', English: '/ˈɪŋɡlɪʃ/',
  Chinese: '/tʃaɪˈniːz/', lost: '/lɔːst/', shoe: '/ʃuː/',
  strong: '/strɔːŋ/', friendly: '/ˈfrendli/', quiet: '/ˈkwaɪət/',
  hair: '/her/', glasses: '/ˈɡlæsɪz/', right: '/raɪt/',
  bedroom: '/ˈbedruːm/', living: '/ˈlɪvɪŋ/', kitchen: '/ˈkɪtʃɪn/',
  bathroom: '/ˈbæθruːm/', study: '/ˈstʌdi/', sofa: '/ˈsoʊfə/',
  fridge: '/frɪdʒ/', table: '/ˈteɪbl/', bed: '/bed/',
  noodle: '/ˈnuːdl/', soup: '/suːp/', beef: '/biːf/', chicken: '/ˈtʃɪkɪn/',
  vegetable: '/ˈvedʒtəbl/', chopsticks: '/ˈtʃɑːpstɪks/', bowl: '/boʊl/',
  fork: '/fɔːrk/', knife: '/naɪf/', spoon: '/spuːn/', dinner: '/ˈdɪnər/',
  pass: '/pæs/', try: '/traɪ/', ready: '/ˈredi/',
  parents: '/ˈperənts/', uncle: '/ˈʌŋkl/', aunt: '/ænt/', baby: '/ˈbeɪbi/',
  cousin: '/ˈkʌzn/', doctor: '/ˈdɑːktər/', cook: '/kʊk/', driver: '/ˈdraɪvər/',
  farmer: '/ˈfɑːrmər/', nurse: '/nɜːrs/', job: '/dʒɑːb/', but: '/bʌt/',
  weather: '/ˈweðər/', cold: '/koʊld/', cool: '/kuːl/', warm: '/wɔːrm/',
  hot: '/hɑːt/', sunny: '/ˈsʌni/', rainy: '/ˈreɪni/', windy: '/ˈwɪndi/',
  cloudy: '/ˈklaʊdi/', snowy: '/ˈsnoʊi/', outside: '/aʊtˈsaɪd/',
  degree: '/dɪˈɡriː/', how: '/haʊ/', about: '/əˈbaʊt/',
  sheep: '/ʃiːp/', cow: '/kaʊ/', horse: '/hɔːrs/', hen: '/hen/',
  lamb: '/læm/', goat: '/ɡoʊt/', farm: '/fɑːrm/', garden: '/ˈɡɑːrdn/',
  tomato: '/təˈmeɪtoʊ/', potato: '/pəˈteɪtoʊ/', carrot: '/ˈkærət/',
  green: '/ɡriːn/', bean: '/biːn/', onion: '/ˈʌnjən/', those: '/ðoʊz/',
  these: '/ðiːz/', yum: '/jʌm/',
  coat: '/koʊt/', shirt: '/ʃɜːrt/', sweater: '/ˈswetər/', jacket: '/ˈdʒækɪt/',
  dress: '/dres/', skirt: '/skɜːrt/', pants: '/pænts/', socks: '/sɑːks/',
  shorts: '/ʃɔːrts/', hat: '/hæt/', clothes: '/kloʊðz/', wear: '/wer/',
  whose: '/huːz/', mine: '/maɪn/', pack: '/pæk/', wait: '/weɪt/',
  pretty: '/ˈprɪti/', cheap: '/tʃiːp/', expensive: '/ɪkˈspensɪv/',
  nice: '/naɪs/', size: '/saɪz/', dollar: '/ˈdɑːlər/', help: '/help/',
  sunglasses: '/ˈsʌnɡlæsɪz/', glove: '/ɡlʌv/', scarf: '/skɑːrf/',
  umbrella: '/ʌmˈbrelə/', shopping: '/ˈʃɑːpɪŋ/',
  // 五年级上下
  old: '/oʊld/', young: '/jʌŋ/', funny: '/ˈfʌni/', kind: '/kaɪnd/',
  strict: '/strɪkt/', polite: '/pəˈlaɪt/', hard: '/hɑːrd/', helpful: '/ˈhelpfl/',
  shy: '/ʃaɪ/', clever: '/ˈklevər/', will: '/wɪl/', sometimes: '/ˈsʌmtaɪmz/',
  Monday: '/ˈmʌndeɪ/', Tuesday: '/ˈtjuːzdeɪ/', Wednesday: '/ˈwenzdeɪ/',
  Thursday: '/ˈθɜːrzdeɪ/', Friday: '/ˈfraɪdeɪ/', Saturday: '/ˈsætərdeɪ/',
  Sunday: '/ˈsʌndeɪ/', weekend: '/ˈwiːkend/', watch: '/wɑːtʃ/',
  read: '/riːd/', play: '/pleɪ/', do: '/duː/', homework: '/ˈhoʊmwɜːrk/',
  often: '/ˈɔːfn/', sometimes: '/ˈsʌmtaɪmz/', wash: '/wɑːʃ/',
  sandwich: '/ˈsænwɪtʃ/', salad: '/ˈsæləd/', hamburger: '/ˈhæmbɜːrɡər/',
  ice: '/aɪs/', cream: '/kriːm/', tea: '/tiː/', fresh: '/freʃ/',
  healthy: '/ˈhelθi/', delicious: '/dɪˈlɪʃəs/', hot: '/hɑːt/',
  sweet: '/swiːt/', favourite: '/ˈfeɪvərɪt/', drink: '/drɪŋk/',
  sing: '/sɪŋ/', dance: '/dæns/', draw: '/drɔː/', swim: '/swɪm/',
  run: '/rʌn/', jump: '/dʒʌmp/', fly: '/flaɪ/', walk: '/wɔːk/',
  climb: '/klaɪm/', can: '/kæn/', any: '/ˈeni/', kungfu: '/kʌŋˈfuː/',
  pipa: '/piːˈpɑː/', cook: '/kʊk/', problem: '/ˈprɑːbləm/',
  robot: '/ˈroʊbɑːt/', speak: '/spiːk/', finish: '/ˈfɪnɪʃ/',
  send: '/send/', email: '/ˈiːmeɪl/', want: '/wɑːnt/',
  clock: '/klɑːk/', plant: '/plænt/', bottle: '/ˈbɑːtl/', bike: '/baɪk/',
  photo: '/ˈfoʊtoʊ/', front: '/frʌnt/', between: '/bɪˈtwiːn/',
  above: '/əˈbʌv/', beside: '/bɪˈsaɪd/', behind: '/bɪˈhaɪnd/',
  forest: '/ˈfɔːrɪst/', lake: '/leɪk/', river: '/ˈrɪvər/', mountain: '/ˈmaʊntn/',
  hill: '/hɪl/', bridge: '/brɪdʒ/', village: '/ˈvɪlɪdʒ/', house: '/haʊs/',
  tree: '/triː/', building: '/ˈbɪldɪŋ/', there: '/ðer/',
  // 五年级下
  spring: '/sprɪŋ/', summer: '/ˈsʌmər/', autumn: '/ˈɔːtəm/', winter: '/ˈwɪntər/',
  season: '/ˈsiːzn/', picnic: '/ˈpɪknɪk/', snowman: '/ˈsnoʊmæn/',
  pick: '/pɪk/', snow: '/snoʊ/', leaf: '/liːf/', paint: '/peɪnt/',
  January: '/ˈdʒænjueri/', February: '/ˈfebrueri/', March: '/mɑːrtʃ/',
  April: '/ˈeɪprəl/', May: '/meɪ/', June: '/dʒuːn/', July: '/dʒuˈlaɪ/',
  August: '/ˈɔːɡəst/', September: '/sepˈtembər/', October: '/ɑːkˈtoʊbər/',
  November: '/noʊˈvembər/', December: '/dɪˈsembər/',
  first: '/fɜːrst/', second: '/ˈsekənd/', third: '/θɜːrd/',
  fourth: '/fɔːrθ/', fifth: '/fɪfθ/', twelfth: '/twelfθ/',
  twentieth: '/ˈtwentiəθ/', special: '/ˈspeʃl/', festival: '/ˈfestɪvl/',
  when: '/wen/', trip: '/trɪp/', national: '/ˈnæʃnəl/',
  keep: '/kiːp/', turn: '/tɜːrn/', quietly: '/ˈkwaɪətli/',
  take: '/teɪk/', each: '/iːtʃ/', other: '/ˈʌðər/', exhibition: '/ˌeksɪˈbɪʃn/',
  say: '/seɪ/', teach: '/tiːtʃ/', sure: '/ʃʊr/',
  mine: '/maɪn/', yours: '/jʊrz/', his: '/hɪz/', hers: '/hɜːrz/',
  theirs: '/ðerz/', ours: '/aʊrz/', eating: '/ˈiːtɪŋ/',
  climbing: '/ˈklaɪmɪŋ/', sleeping: '/ˈsliːpɪŋ/', jumping: '/ˈdʒʌmpɪŋ/',
  drinking: '/ˈdrɪŋkɪŋ/', playing: '/ˈpleɪɪŋ/', listening: '/ˈlɪsnɪŋ/',
  reading: '/ˈriːdɪŋ/', running: '/ˈrʌnɪŋ/', swimming: '/ˈswɪmɪŋ/',
  exercise: '/ˈeksərsaɪz/', bamboo: '/bæmˈbuː/',
  start: '/stɑːrt/', always: '/ˈɔːlweɪz/', usually: '/ˈjuːʒuəli/',
  sometimes: '/ˈsʌmtaɪmz/', never: '/ˈnevər/', excited: '/ɪkˈsaɪtɪd/',
  world: '/wɜːrld/', show: '/ʃoʊ/', island: '/ˈaɪlənd/', cave: '/keɪv/',
  win: '/wɪn/', sound: '/saʊnd/', think: '/θɪŋk/', work: '/wɜːrk/',
  still: '/stɪl/', last: '/læst/', also: '/ˈɔːlsoʊ/', either: '/ˈaɪðər/',
  // Common verbs/adjectives
  go: '/ɡoʊ/', come: '/kʌm/', get: '/ɡet/', make: '/meɪk/', know: '/noʊ/',
  new: '/njuː/', good: '/ɡʊd/', great: '/ɡreɪt/', little: '/ˈlɪtl/',
  different: '/ˈdɪfrənt/', same: '/seɪm/', important: '/ɪmˈpɔːrtnt/',
  next: '/nekst/', today: '/təˈdeɪ/', tomorrow: '/təˈmɑːroʊ/',
  yesterday: '/ˈjestərdeɪ/', morning: '/ˈmɔːrnɪŋ/', afternoon: '/ˌæftərˈnuːn/',
  evening: '/ˈiːvnɪŋ/', night: '/naɪt/', time: '/taɪm/', day: '/deɪ/',
  week: '/wiːk/', month: '/mʌnθ/', year: '/jɪr/', now: '/naʊ/',
  just: '/dʒʌst/', very: '/ˈveri/', much: '/mʌtʃ/', well: '/wel/',
  too: '/tuː/', really: '/ˈriːəli/', soon: '/suːn/', back: '/bæk/',
  away: '/əˈweɪ/', home: '/hoʊm/', place: '/pleɪs/', thing: '/θɪŋ/',
  people: '/ˈpiːpl/', friend: '/frend/', class: '/klæs/', game: '/ɡeɪm/',
  name: '/neɪm/', word: '/wɜːrd/', story: '/ˈstɔːri/', song: '/sɔːŋ/',
  color: '/ˈkʌlər/', flower: '/ˈflaʊər/', rain: '/reɪn/', wind: '/wɪnd/',
  sun: '/sʌn/', moon: '/muːn/', star: '/stɑːr/', sky: '/skaɪ/',
  // 六年级常见词
  science: '/ˈsaɪəns/', museum: '/mjuˈziːəm/', cinema: '/ˈsɪnəmə/',
  hospital: '/ˈhɑːspɪtl/', library: '/ˈlaɪbreri/', restaurant: '/ˈrestrɑːnt/',
  park: '/pɑːrk/', hotel: '/hoʊˈtel/', gym: '/dʒɪm/', cross: '/krɔːs/',
  turn: '/tɜːrn/', left: '/left/', right: '/raɪt/', straight: '/streɪt/',
  street: '/striːt/', far: '/fɑːr/', follow: '/ˈfɑːloʊ/', pizza: '/ˈpiːtsə/',
  by: '/baɪ/', bus: '/bʌs/', train: '/treɪn/', taxi: '/ˈtæksi/',
  plane: '/pleɪn/', ship: '/ʃɪp/', subway: '/ˈsʌbweɪ/', stop: '/stɑːp/',
  slow: '/sloʊ/', fast: '/fæst/', visit: '/ˈvɪzɪt/', half: '/hæf/',
  price: '/praɪs/', together: '/təˈɡeðər/', tomorrow: '/təˈmɑːroʊ/',
  evening: '/ˈiːvnɪŋ/', deep: '/diːp/', breath: '/breθ/', count: '/kaʊnt/',
  bad: '/bæd/', hurt: '/hɜːrt/', should: '/ʃʊd/', feel: '/fiːl/',
  worry: '/ˈwɜːri/', stuck: '/stʌk/', pull: '/pʊl/', everyone: '/ˈevriwʌn/',
  sad: '/sæd/', angry: '/ˈæŋɡri/', afraid: '/əˈfreɪd/', happy: '/ˈhæpi/',
  worried: '/ˈwɜːrid/', wear: '/wer/', more: '/mɔːr/', ant: '/ænt/',
  grass: '/ɡræs/', mud: '/mʌd/', pilot: '/ˈpaɪlət/', coach: '/koʊtʃ/',
  fisherman: '/ˈfɪʃərmən/', scientist: '/ˈsaɪəntɪst/', reporter: '/rɪˈpɔːrtər/',
  secretary: '/ˈsekrəteri/', businessman: '/ˈbɪznəsmæn/', factory: '/ˈfæktəri/',
  worker: '/ˈwɜːrkər/', postman: '/ˈpoʊstmən/', police: '/pəˈliːs/',
  taller: '/ˈtɔːlər/', shorter: '/ˈʃɔːrtər/', older: '/ˈoʊldər/',
  younger: '/ˈjʌŋər/', stronger: '/ˈstrɔːŋər/', bigger: '/ˈbɪɡər/',
  thinner: '/ˈθɪnər/', heavier: '/ˈheviər/', longer: '/ˈlɔːŋər/',
  smaller: '/ˈsmɔːlər/', dinosaur: '/ˈdaɪnəsɔːr/', hall: '/hɔːl/',
  metre: '/ˈmiːtər/', become: '/bɪˈkʌm/', shadow: '/ˈʃædoʊ/',
  smarter: '/ˈsmɑːrtər/', ago: '/əˈɡoʊ/', cycling: '/ˈsaɪklɪŋ/',
  badminton: '/ˈbædmɪntən/', 'ice-skate': '/aɪs skeɪt/', dream: '/driːm/',
  race: '/reɪs/', thought: '/θɔːt/', felt: '/felt/', woke: '/woʊk/',
  before: '/bɪˈfɔːr/', grass: '/ɡræs/', gym: '/dʒɪm/', ago: '/əˈɡoʊ/',
  nothing: '/ˈnʌθɪŋ/', active: '/ˈæktɪv/', different: '/ˈdɪfrənt/',
  easy: '/ˈiːzi/', life: '/laɪf/', change: '/tʃeɪndʒ/',
}

export function getPhonetic(word) {
  const key = word?.toLowerCase?.() || ''
  return phoneticDB[key] || null
}

export default phoneticDB
